sudo: false
language: node_js
env:
  - PUBLISH_FROM_NODE_VERSION=8.4
node_js:
  - "8.4"
  - "node"
before_install:
  - npm install -g npm@latest
before_script:
  - npm run build
after_success:
  - ./.travis_publish
cache:
  directories:
    - node_modules
